# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  system.debugContext: 'true' # o 'false' según tu requerimiento
resources:
  repositories:
    - repository: self
      type: git
      name: js-e2e-express-server-test
      checkoutOptions:
        fetchDepth: 1


steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'
